project:
  type: book
  output-dir: _book

book:
  title: "Molecular Tumor Board — Simulation Handbook"
  author: "Prof. XXXX"
  date: 2025-08-30
  chapters:
    - index.qmd
    - 01_avvio.qmd
    - 02_framework.qmd
    - 03_glioma.qmd
    - 04_ovaio.qmd
    - 05_breast.qmd
    - 07_fusion.qmd
    - 08_Fusion2.qmd
    - 09_LLM_clinical_local.qmd


format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-copy: true
    df-print: paged
    css: assets/styles.css

execute:
  echo: true
  warning: false
  message: false
  freeze: auto

lang: it
bibliography: references.bib
